### PR TITLE
Update web_assets.json

### PR DESCRIPTION
**Pull request by brianteeman**
as requested https://github.com/joomla/joomla-cms/issues/36530

I have not tested or verified this I just did a PR

### CODE REVIEW

**Comment by richard67** [comment]
@brianteeman Does this PR solve the CMS issue so we can close that?

**Comment by brianteeman** [comment]
only if it works.

**Comment by richard67** [comment]
And when will we know that? When this has been merged here? I just don't want that we forget about to close the issue later.

**Comment by brianteeman** [comment]
Well hopefully someone will test it. I really have no idea about this. I dont know where its used or how to see a problem

**Comment by wilsonge** [comment]
https://json-schema.org/learn/getting-started-step-by-step.html
This is a doc about how json schema works. Basically it allows validation of the properties in a json file (specifically here web assets but it’s generic). If you see in any web assets file we define a $schema property at the top (e.g. https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/com_banners/joomla.asset.json#L2)

There’s a decent’ish blog here about why it’s useful https://nickymeuleman.netlify.app/blog/json-schema/
You can test by using an online validation service for both a sample file and this schema (e.g. https://www.jsonschemavalidator.net/). Most IDE’s (definitely VSCode and anything JetBrains - list of compat IDE’s is https://json-schema.org/implementations.html#editors) also do validation automatically when the schema is present. You can also change the path of the schema to be a local file path rather than a url for testing). I suspect there’s tools to do local validation without an IDE too - but honestly I haven’t gone hunting.

just for what it’s worth from my train this PR looks good - but can’t hurt to test - the more you know and all that. But I’ll also look properly this evening or tomorrow

**Comment by wilsonge** [comment]
thankyou @brianteeman all looks good

**Comment by brianteeman** [comment]
Thanks

**Comment by richard67** [comment]
So can we close the CMS issue?

**Comment by brianteeman** [comment]
Yes - I marked it there as can be closed

**Pull request merged**
