### PR TITLE
Update asset schema: importmap properties

### PR DESCRIPTION
**Pull request by Fedik**
The PR adds properties for `importmap`.
See https://github.com/joomla/joomla-cms/pull/40714 "ESM importmap support"

### CODE REVIEW

**Comment by Fedik** [comment]
Can test here https://www.jsonschemavalidator.net/
Copy whole schema from the PR, and use your json for assets.
Or this one:
```
{
  "name": "test",
  "version": "11",
  "description": "description",  
  "assets": [
    {
      "name": "a",
      "type": "script",
      "importmap": true,
      "importmapName": "aaa",
      "importmapScope": "bbb"
    }
  ]	
}
```

**Comment by HLeithner** [comment]
the content .gitignore should be part of your global .gitignore file not of this repo

**Comment by Fedik** [comment]
It a default gitignore we should have in all repos,
Why this repo should have an exception?

**Comment by HLeithner** [comment]
the content you commit was something that should be in the global ignore file for each person using git but yep true I thought joomla did it the right way but isn't ;-)

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
